version: '3.10'
author: Pycrafters - Kagev
licence: G
services:

  app:
    image: fastapi-project-image
    container_name: fastapi-project-container
    build: .
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/app

    environment:
      # The environment variables from your .env file
      # are automatically loaded into the container
      for key, value in os.environ.items():
        environment[key] = value