"""tyctyc

Revision ID: 412c1fbac635
Revises: 2de1c760ccdf
Create Date: 2023-10-19 12:12:53.501683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '412c1fbac635'
down_revision: Union[str, None] = '2de1c760ccdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloudinary_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('resource_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.String(), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('secure_url', sa.String(), nullable=True),
    sa.Column('next_cursor', sa.String(), nullable=True),
    sa.Column('transformation', sa.String(), nullable=True),
    sa.Column('pages', sa.String(), nullable=True),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('images', sa.Column('image_name', sa.String(), nullable=True))
    op.add_column('images', sa.Column('qr_code', sa.Text(), nullable=True))
    op.create_index(op.f('ix_images_image_name'), 'images', ['image_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_images_image_name'), table_name='images')
    op.drop_column('images', 'qr_code')
    op.drop_column('images', 'image_name')
    op.drop_table('cloudinary_resources')
    # ### end Alembic commands ###
