"""tyctyc-2

Revision ID: 4e555941e5d7
Revises: 412c1fbac635
Create Date: 2023-10-19 12:46:43.141468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e555941e5d7'
down_revision: Union[str, None] = '412c1fbac635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cloudinary_resources_image_id_fkey', 'cloudinary_resources', type_='foreignkey')
    op.drop_column('cloudinary_resources', 'image_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cloudinary_resources', sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('cloudinary_resources_image_id_fkey', 'cloudinary_resources', 'images', ['image_id'], ['id'])
    # ### end Alembic commands ###
