"""qrcode_v2

Revision ID: 52d08103ee1b
Revises: bcc35f18a7e4
Create Date: 2023-10-22 21:15:40.956923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52d08103ee1b'
down_revision: Union[str, None] = 'bcc35f18a7e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_image_resources', sa.Column('img_transform_url', sa.String(length=255), nullable=False))
    op.add_column('qr_image_resources', sa.Column('qr_code_url', sa.Text(), nullable=False))
    op.drop_column('qr_image_resources', 'url')
    op.drop_column('qr_image_resources', 'qr_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_image_resources', sa.Column('qr_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('qr_image_resources', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('qr_image_resources', 'qr_code_url')
    op.drop_column('qr_image_resources', 'img_transform_url')
    # ### end Alembic commands ###
