"""qrcode_v3

Revision ID: f0e55cbd3497
Revises: 52d08103ee1b
Create Date: 2023-10-22 23:52:51.166557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e55cbd3497'
down_revision: Union[str, None] = '52d08103ee1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_image_resources', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('qr_image_resources', 'created_at')
    # ### end Alembic commands ###
